#!/bin/bash
set -e

DIR=$(cd `dirname $0` && pwd)

if [ ! -d $HOME/.oh-my-zsh ]; then
  git clone https://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
fi

for dotfile in zshrc gemrc irbrc; do
  ln -nfs $DIR/$dotfile $HOME/.$dotfile
done
